org: bureck
service: nodejs-aws-lambda
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  apiGateway:
    shouldStartNameWithService: true
    cors:
      origin: '*'
      headers:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Requested-With
      allowCredentials: false
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-offline
package:
  include:
    - src/views/**
  patterns:
    - 'src/**'
    - 'src/views/**'
    - '!node_modules/**'
    - '!.git/**'
    - '!test/**'

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
  serverless-offline:
    noPrependStageInUrl: true